import { NextResponse } from "next/server";
import { documentStatus, fieldNames, LocalBillRepository, toPublicDocument, type FieldName } from "@/app/lib/foundation/real-bill";

const audit = { async record(event: { readonly type: string; readonly tenantId: string; readonly documentId: string; readonly outcome: string }) { console.info("foundation-audit", { ...event }); } };

export async function GET(request: Request, context: { params: Promise<{ id: string }> }): Promise<Response> { const tenantId = request.headers.get("x-foundation-tenant-id"); if (!tenantId || process.env.FOUNDATION_LOCAL_DEV !== "true") return NextResponse.json({ error: "TENANT_ACCESS_DENIED" }, { status: 403 }); const { id } = await context.params; const document = await new LocalBillRepository().get(tenantId, id); return document ? NextResponse.json({ document: toPublicDocument(document) }) : NextResponse.json({ error: "DOCUMENT_NOT_FOUND" }, { status: 404 }); }

export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }): Promise<Response> { const tenantId = request.headers.get("x-foundation-tenant-id"); if (!tenantId || process.env.FOUNDATION_LOCAL_DEV !== "true") return NextResponse.json({ error: "TENANT_ACCESS_DENIED" }, { status: 403 }); const { id } = await context.params; const body: unknown = await request.json(); if (!isCorrection(body)) return NextResponse.json({ error: "CORRECTION_INVALID" }, { status: 400 }); const repository = new LocalBillRepository(); const document = await repository.get(tenantId, id); if (!document) return NextResponse.json({ error: "DOCUMENT_NOT_FOUND" }, { status: 404 }); const fields = { ...document.fields, [body.field]: { value: body.value, confidence: 1, source: "manual" as const, confirmed: true } }; const updated = { ...document, fields, status: documentStatus(fields), updatedAt: new Date().toISOString() }; await repository.save(updated); await audit.record({ type: "MANUAL_REVIEW", tenantId, documentId: id, outcome: "ALLOWED" }); await audit.record({ type: "CORRECTION", tenantId, documentId: id, outcome: "ALLOWED" }); return NextResponse.json({ document: toPublicDocument(updated) }); }
function isCorrection(value: unknown): value is { field: FieldName; value: string } { if (typeof value !== "object" || value === null) return false; const record = value as Record<string, unknown>; return typeof record.field === "string" && fieldNames.includes(record.field as FieldName) && typeof record.value === "string" && record.value.trim().length > 0 && record.value.length <= 500; }
