import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { legacyCteApprovedSnapshot } from "../app/lib/cte/approved-snapshot.ts";
import { toPublicCteApprovedArchiveDetail } from "../app/lib/cte/archive/service.ts";
import { LocalCteArchiveRepository } from "../app/lib/cte/archive/repository.ts";
import { normalizeCteReview } from "../app/lib/cte/review.ts";

const tenant = "tenant_local-demo";
const ingestion = JSON.parse(await readFile("var/phase6/cte-archives/tenant_local-demo/cte-ingestion-c30431e0-11ab-460d-ad10-6a26eb23b63d.json", "utf8"));
const archive = await new LocalCteArchiveRepository().get(tenant, ingestion.recordId);
assert.ok(archive?.currentApprovedVersionId);
const approvedVersion = archive.versions.find((version) => version.versionId === archive.currentApprovedVersionId);
assert.ok(approvedVersion);
const snapshot = legacyCteApprovedSnapshot({ record: ingestion.payload, tenantId: tenant, contract: approvedVersion.contract });
const detail = toPublicCteApprovedArchiveDetail(archive, snapshot);
assert.ok(detail);
const fields = new Map([...snapshot.reviewFields, ...snapshot.notFoundFields].map((field) => [field.fieldKey, field]));
assert.equal(fields.get("offer.name")?.normalizedValue, "Be Relax 06.25");
assert.equal(fields.get("eligibility.customerTypes")?.normalizedValue, "Non domestico – Altri usi Business");
assert.equal(fields.get("eligibility.consumptionRange")?.normalizedValue, "Oltre 1.500 e fino a 200.000 kWh/anno");
assert.deepEqual(fields.get("eligibility.voltageLevels")?.normalizedValue, "BT / MT");
assert.deepEqual(fields.get("eligibility.exclusions")?.normalizedValue, ["Pubblica illuminazione", "Pubblica Amministrazione", "Enti pubblici"]);
assert.equal(fields.get("pricing.mode")?.normalizedValue, "Indicizzata");
assert.equal(fields.get("pricing.reference")?.normalizedValue, "PUN");
assert.equal(fields.get("pricing.spread.amount")?.normalizedValue, 0.025);
assert.equal(fields.get("commercialTerms.fixedFees")?.normalizedValue, 15);
assert.equal(fields.get("commercialTerms.variableFees")?.normalizedValue, 0.003);
assert.equal(fields.get("commercialTerms.imbalance")?.normalizedValue, 0.005);
assert.equal(fields.get("commercialTerms.oneOffFees")?.normalizedValue, 1.5);
assert.equal(fields.get("commercialTerms.oneOffFees")?.description, "Gestione APP e servizi di €1,50");
assert.equal(fields.get("taxTreatment")?.normalizedValue, "IVA e imposte escluse");
assert.equal(detail.contract.reviewFields?.find((field) => field.fieldKey === "eligibility.consumptionRange")?.normalizedValue, "Oltre 1.500 e fino a 200.000 kWh/anno");
assert.doesNotMatch(JSON.stringify(detail), /objectKey|ingestionId|recordId|feeId/);
assert.equal(normalizeCteReview(ingestion.payload).commercialFields.length, snapshot.reviewFields.length);
console.log("approved CTE archive smoke: ok (real persisted approval snapshot compatibility and exact review values)");
