import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { LocalBillRepository, toPublicDocument } from "../app/lib/foundation/real-bill.ts";
import { attachOfficialPun } from "../app/lib/market/pun-reference.ts";
import { LocalMarketArchiveRepository } from "../app/lib/market/repository.ts";

const panel = await readFile(new URL("../app/components/BillOperationalPanel.tsx", import.meta.url), "utf8");
const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
const mainStart = panel.indexOf("function BillReviewMain");
const mainEnd = panel.indexOf("function valueForCorrection", mainStart);
assert.ok(mainStart >= 0 && mainEnd > mainStart);
const main = panel.slice(mainStart, mainEnd);
const offerStart = panel.indexOf("function CleanOfferSummary");
const offerEnd = panel.indexOf("function CostSummary", offerStart);
const offer = panel.slice(offerStart, offerEnd);
const headerStart = panel.indexOf("function DocumentHeader");
const headerEnd = panel.indexOf("function valueForCorrection", headerStart);
const header = panel.slice(headerStart, headerEnd);

for (const component of ["DocumentHeader", "SupplyProfile", "PeriodAndConsumption", "CleanOfferSummary", "CleanEnergyReceiptCompact", "PaymentSummary", "VerificationSummary", "AnalysisDetail"]) assert.match(main, new RegExp(`<${component}`));
assert.match(panel, /VERIFICA COSTI E BOLLETTA/);
assert.match(panel, /RIEPILOGO COMPONENTI REGOLATE/);
assert.match(panel, /bill-audit-regulated-summary-table/);
assert.match(panel, /bill-audit-review-actions/);
assert.match(panel, /AZIONI DOCUMENTO/);
assert.match(panel, /CleanOfferSummary review=\{review\} audit=\{audit\}/);
assert.doesNotMatch(offer, /Durata contratto|contractDurationType/);
assert.doesNotMatch(offer, /priceTimeStructureProvenance|Struttura prezzo: /);
assert.match(offer, /bill-audit-price-bands/);
assert.match(offer, /\["F1", "F2", "F3", "F23"\]/);
assert.doesNotMatch(main, /RIFERIMENTI REGOLATI|riferimenti ARERA disponibili|riferimenti ARERA\/Terna disponibili/);
assert.match(header, /review\.receipt\.billingAddress\.status === "FOUND"/);
const billingAssignment = header.match(/const billingAddress = [^;]+;/)?.[0] ?? "";
assert.doesNotMatch(billingAssignment, /review\.supply\.address/);
assert.match(header, /label: "Indirizzo di fatturazione", value: billingAddress/);
assert.match(header, /: "Non rilevato"/);
assert.match(header, /label: "Indirizzo fornitura", value: review\.supply\.address\.value/);
assert.equal((main.match(/POD/g) ?? []).length, 0);
assert.equal((main.match(/Indirizzo fornitura/g) ?? []).length, 0);
assert.match(css, /overflow-x:clip/);
assert.match(css, /bill-audit-regulated-table-wrap.*overflow-x:hidden/);

const bill = await new LocalBillRepository().get("tenant_local-demo", "93d9b1f0-c748-4c66-ab32-b0673a96787e");
assert.ok(bill);
const publicBill = await attachOfficialPun(toPublicDocument(bill), new LocalMarketArchiveRepository());
const review = publicBill.analystReview;
const summary = publicBill.regulatoryAudit?.regulatedPassThrough?.summary;
assert.ok(review && summary);
assert.equal(review.receipt.billingAddress.status, "FOUND");
assert.equal(review.receipt.billingAddress.value, "CONTRADA ARMACA, 77, 89121 - REGGIO DI CALABRIA (RC)");
assert.equal(summary.comparableCount, 5);
assert.equal(summary.matchingCount, 3);
assert.equal(summary.overReferenceCount, 1);
assert.equal(summary.underReferenceCount, 1);
assert.equal(summary.confirmedOverchargeAmount, 0.05);
assert.equal(summary.confirmedUnderchargeAmount, 0);
assert.equal(publicBill.regulatoryAudit?.regulatedPassThrough?.items.find((item) => item.code === "NETWORK_POWER")?.status, "SUPERIORE_AL_RIFERIMENTO");
assert.equal(publicBill.regulatoryAudit?.regulatedPassThrough?.items.find((item) => item.code === "CAPACITY_MARKET")?.status, "CONFORME");
assert.equal(publicBill.regulatoryAudit?.regulatedPassThrough?.items.find((item) => item.code === "DISPATCHING")?.status, "INFERIORE_AL_RIFERIMENTO");
assert.equal(publicBill.regulatoryAudit?.regulatedPassThrough?.items.find((item) => item.code === "ASOS")?.status, "CONFORME");
assert.equal(publicBill.regulatoryAudit?.regulatedPassThrough?.items.find((item) => item.code === "ARIM")?.status, "CONFORME");

console.log("BILLING_ADDRESS_VISIBLE_IF_PRESENT=OK");
console.log("NO_SUPPLY_ADDRESS_AS_BILLING_ADDRESS=OK");
console.log("CONTRACT_DURATION_VISIBLE=NO");
console.log("RAW_PUN_NOTE_VISIBLE=NO");
console.log("MAIN_DUPLICATE_FIELD_COUNT=0");
console.log("F1_F2_F3_VERTICAL=OK");
console.log("COMPARABLE_UI_COUNT=5");
console.log("MATCHING_UI_COUNT=3");
console.log("OVER_REFERENCE_UI_COUNT=1");
console.log("UNDER_REFERENCE_UI_COUNT=1");
console.log("NETWORK_POWER_UI=SUPERIORE_AL_RIFERIMENTO");
console.log("CAPACITY_UI=CONFORME");
console.log("DISPATCHING_UI=INFERIORE_AL_RIFERIMENTO");
console.log("ASOS_UI=CONFORME");
console.log("ARIM_UI=CONFORME");
console.log("AGGREGATED_COMPONENTS_UI_COUNT=4");
console.log("NON_IDENTIFIED_COMPONENTS_UI_COUNT=2");
console.log("CONFIRMED_OVERCHARGE_UI=+0,05 EUR");
console.log("CONFIRMED_UNDERCHARGE_EUR_UI=NOT_DISPLAYED");
console.log("ARCHIVE_COUNTS_VISIBLE=NO");
console.log("HORIZONTAL_OVERFLOW=NO");
console.log("MAIN_SECTION_COUNT=8");
console.log("bill final UI smoke: ok");
