import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildBillAnalystReview } from "../app/lib/foundation/bill-analyst-review.ts";

const found = (value) => ({ value, status: "FOUND", confidence: 0.9, source: "DOCUMENT_AI" });
const notFound = () => ({ value: null, status: "NOT_FOUND", confidence: 0, source: "DOCUMENT_AI" });
const fields = { supplier: found("Supplier fixture"), pod: found("IT001E12345678"), customerName: found("Customer fixture"), billingPeriod: found({ from: "2026-06-01", to: "2026-07-01", raw: "01/06/2026 - 30/06/2026" }), annualConsumption: found(1200), billedConsumption: found(100), totalAmount: found(80), customerId: notFound(), customerType: found("RESIDENTIAL"), customerTaxIdentifier: found("TAX-FIXTURE"), vector: found("EE"), pdr: notFound(), voltageLevel: found("LV"), powerKw: found(3), f1Consumption: found(30), f2Consumption: found(30), f3Consumption: found(40), smcConsumption: notFound(), conversionCoefficient: notFound(), pcs: notFound(), offerName: found("Hidden offer"), offerCode: found("HIDDEN-CODE") };
const extraction = { schemaVersion: 1, ...fields, extendedFacts: [{ code: "SUPPLY_ADDRESS", value: "Supply address fixture", status: "FOUND" }, { code: "NOMINAL_SUPPLY_VOLTAGE", value: "230 V", status: "FOUND" }, { code: "POWER_COMMITTED", value: "3 kW", status: "FOUND" }, { code: "BILL_ISSUE_DATE", value: "02/07/2026", status: "FOUND" }, { code: "BILL_DUE_DATE", value: "16/07/2026", status: "FOUND" }, { code: "CONTRACT_INDEFINITE", value: "true", status: "FOUND" }, { code: "PUN_F1", value: "110", unit: "EUR/KWH", status: "FOUND" }, { code: "SPREAD", value: "0,012", status: "FOUND" }], economicChargeLines: [{ code: "DISPATCHING", description: "Dispacciamento", quantity: "100", unit: "EUR/KWH", unitPrice: "0,01", amount: "1,00", periodRaw: "06/2026", status: "FOUND" }, { code: "VAT", description: "IVA", quantity: "1", unit: "EUR", unitPrice: "10%", amount: "8,00", periodRaw: "06/2026", status: "FOUND" }] };
const emptyFields = { supplier: notFound(), pod: notFound(), customerName: notFound(), billingPeriod: notFound(), annualConsumption: notFound(), billedConsumption: notFound(), totalAmount: notFound() };
const review = buildBillAnalystReview({ id: "bill-fixture", fileName: "fixture.pdf", status: "REVIEW_REQUIRED", reviewState: "WORKING", currentVersionNumber: 1, approvalReady: false, updatedAt: "2026-07-02T00:00:00.000Z", fields: emptyFields, normalized: null, structuredBill: extraction, resolvedVector: "EE", invoicePunReferences: [] });
assert.equal(review.document.fileName, "fixture.pdf");
assert.equal(review.supply.address.status, "FOUND");
assert.equal(review.supply.nominalSupplyVoltage.value, "230 V");
assert.equal(review.dates.billingPeriodRaw.value, "01/06/2026 - 30/06/2026");
assert.equal(review.economics.chargeLines.length, 2);
assert.equal(Object.prototype.hasOwnProperty.call(review, "offerName"), false);

const panel = await readFile(new URL("../app/components/BillOperationalPanel.tsx", import.meta.url), "utf8");
const dto = await readFile(new URL("../app/lib/foundation/bill-analyst-review.ts", import.meta.url), "utf8");
for (const label of ["Livello tensione", "Stato elaborazione"]) assert.equal(panel.includes(label), false, `banned main UI label: ${label}`);
assert.match(panel, /bill\.analystReview/);
assert.doesNotMatch(panel.slice(panel.indexOf("if (Boolean(review)) return"), panel.indexOf("\n  return <div className=\"bill-audit-detail\"><DocumentHeader")), /VARIABLE/);
assert.doesNotMatch(panel, /bill\.(normalized|structuredBill|fields)/);
assert.doesNotMatch(panel, /PERIODO \/ OFFERTA/);
assert.doesNotMatch(panel, /voltageLevel/);
assert.match(panel, /Da verificare/);
for (const label of ["Indice", "CONSUMI", "OFFERTA ATTUALE", "SCONTRINO DELL", "VERIFICA BOLLETTA", "DETTAGLIO ANALISI", "PROVENIENZA DOCUMENTALE"]) assert.match(panel, new RegExp(label));
assert.match(dto, /export function buildBillAnalystReview/);
assert.match(dto, /readonly punReferences/);
assert.match(dto, /readonly chargeLines/);
assert.match(dto, /readonly reviewIssues/);
console.log("NO_DUPLICATE_PERIOD=OK");
console.log("SUPPLY_PROFILE_RENDERING=OK");
console.log("PERIOD_AND_CONSUMPTION_RENDERING=OK");
console.log("INDEFINITE_CONTRACT_SINGLE_ROW=OK");
console.log("ECONOMIC_CHARGES_RENDERING=OK");
console.log("NO_EMPTY_CARDS=OK");
console.log("NO_DUPLICATE_FIELDS=OK");
console.log("bill analyst review acceptance smoke: ok");
