import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildBillRegulatoryAudit } from "../app/lib/foundation/bill-public-audit.ts";
import { LocalBillRepository, toPublicDocument } from "../app/lib/foundation/real-bill.ts";
import { LocalFilesystemAdapter } from "../app/lib/persistence/local.ts";
import { ProductionRegulatoryPersistenceBridge } from "../app/lib/regulatory-bridge.ts";
import { formatNumber } from "../app/lib/ui/format.ts";
import { loadLocalRuntimeEnvForTests } from "./support/standalone-runtime-env.mjs";

loadLocalRuntimeEnvForTests({ expectedTenantId: "tenant_qa-company" });

const root = "var/qa-bill-hierarchy/foundation-documents";
const archive = JSON.parse(await readFile(root + "/metadata.json", "utf8"));
const source = archive.documents.find((item) => item.fileName === "EE17976_2026_DOLCI_PENSIERI_SRL.pdf");
assert.ok(source);
assert.equal(source.tenantId, "tenant_qa-company");
const document = await new LocalBillRepository(root).get(source.tenantId, source.id);
assert.ok(document);
const publicDocument = toPublicDocument(document);
const review = publicDocument.analystReview;
assert.ok(review);
const analysis = review.economics.economicAnalysis;
const totals = analysis.totals;
const parse = (value) => Number(String(value).includes(",") ? String(value).replace(/\./g, "").replace(",", ".") : value);

assert.equal(publicDocument.structuredBill?.customerType?.value, "NON_RESIDENTIAL");
assert.deepEqual(publicDocument.structuredBill?.billingPeriod?.value, { from: "2026-08-01", to: "2026-08-31", raw: "01/08/2026 - 31/08/2026" });
assert.equal(publicDocument.analystReview?.dates.billIssueDate.value, "09.09.2026");
assert.equal(totals.billTotal, 3060.52);
assert.equal(totals.currentInvoiceAtomicTotal, 3060.52);
assert.equal(totals.currentInvoiceAggregateTotal, 3060.52);
assert.equal(totals.fiscalTotal, 647.44);
assert.equal(totals.extraordinaryTotal, 97.04);
assert.equal(totals.reconciliationDifference, 0);
assert.equal(totals.reconciliationStatus, "RECONCILED");

const fiscalLines = analysis.components.filter((item) => ["ACCISE", "IVA"].includes(item.classification) && item.includedInReconciliation);
assert.deepEqual(fiscalLines.map((item) => [item.classification, item.amount]), [["ACCISE", "95.54"], ["IVA", "551.9"]]);
assert.equal(Math.round(fiscalLines.reduce((sum, item) => sum + parse(item.amount), 0) * 100) / 100, 647.44);
const extraordinaryLines = analysis.components.filter((item) => item.classification === "ALTRE_PARTITE" && item.includedInReconciliation);
assert.deepEqual(extraordinaryLines.map((item) => [item.description, item.amount]), [["Quota variabile smart (CVS)", "20.61"], ["Quota variabile voci di trasporto", "76.43"]]);
assert.equal(Math.round(extraordinaryLines.reduce((sum, item) => sum + parse(item.amount), 0) * 100) / 100, 97.04);
assert.equal(totals.otherItemsTotal, 122.61);

const runtime = new LocalFilesystemAdapter("var/phase6");
const readback = await new ProductionRegulatoryPersistenceBridge(runtime.collection("regulatory-values"), runtime.collection("regulatory-approval-domains")).list(source.tenantId, { effectiveAt: "2026-08-01" });
assert.equal(readback.some((record) => record.componentCode === "ASOS" && record.customerScope === "NON_DOMESTIC_BT_BTA6"), true);
assert.equal(readback.some((record) => record.componentCode === "ARIM" && record.customerScope === "NON_DOMESTIC_BT_BTA6"), true);
const audit = await buildBillRegulatoryAudit(publicDocument);
assert.ok(audit?.regulatedPassThrough);
const items = audit.regulatedPassThrough.items;
const item = (code) => items.find((candidate) => candidate.code === code);
assert.equal(item("UC3")?.comparable, true);
assert.equal(item("UC3")?.billAmount, 21.09);
assert.equal(item("METERING_FIXED")?.comparable, true);
assert.equal(item("METERING_FIXED")?.officialIdentifier, "575/2025/R/eel:TIME:Tabella 1:MIS1");
assert.equal(item("TRANSMISSION_ENERGY")?.comparable, true);
assert.equal(item("TRANSMISSION_ENERGY")?.officialIdentifier, "ARERA_TRAS_2026:Altre utenze in bassa tensione");
assert.equal(item("UC6_FIXED")?.comparable, true);
assert.equal(item("UC6_FIXED")?.billAmount, 0.14);
assert.equal(item("UC6_POWER")?.comparable, false);
assert.equal(item("UC6_POWER")?.reasonCode, "OFFICIAL_REFERENCE_MISSING");
assert.equal(item("UC6_POWER")?.semanticCategory, "REGULATED_ARERA");
assert.match(item("UC6_POWER")?.humanReason ?? "", /Riferimento ARERA individuato/);
assert.equal(item("UC6_POWER")?.billAmount, 0);
assert.equal(item("UC6_ENERGY")?.comparable, true);
assert.equal(item("ASOS")?.comparable, true);
assert.equal(item("ARIM")?.comparable, true);
assert.equal(item("UC6_ENERGY")?.billAmount, 0.54);

const nonComparable = items.filter((candidate) => !candidate.comparable);
const summary = audit.regulatedPassThrough.summary;
assert.equal(summary.nonComparableCount + summary.notIdentifiedCount + summary.officialReferenceMissingCount, 3);
assert.equal(nonComparable.length, 3);
assert.deepEqual(nonComparable.map((candidate) => candidate.code), ["UC6_POWER", "DISPATCHING", "CAPACITY_MARKET"]);
assert.ok(nonComparable.every((candidate) => candidate.reasonCode && candidate.humanReason));
assert.equal(item("DISPATCHING")?.semanticCategory, "CONTRACTUAL_SELLER");
assert.match(item("DISPATCHING")?.humanReason ?? "", /Voce contrattuale del venditore/);
assert.equal(item("CAPACITY_MARKET")?.semanticCategory, "REGULATED_NOT_SEMANTICALLY_EQUIVALENT");
assert.match(item("CAPACITY_MARKET")?.humanReason ?? "", /non è equivalente/);

const atomicTotal = analysis.components.filter((candidate) => candidate.includedInReconciliation).reduce((sum, candidate) => sum + parse(candidate.amount), 0);
assert.equal(Math.round(atomicTotal * 100) / 100, 3060.52);
const ui = await readFile("app/components/BillOperationalPanel.tsx", "utf8");
assert.match(ui, /Altre partite \/ voci straordinarie/);
assert.match(ui, /Vedi dettaglio/);
assert.match(ui, /summary.details/);
assert.match(ui, /Non confrontabile/);
assert.match(ui, /\.\.\.\(totals\.tvFeeTotal !== null \? \[\{ label: "Canone TV"/);
assert.doesNotMatch(ui, /label: "Canone TV", value: totals\.tvFeeTotal === null \? "Da verificare"/);
const css = await readFile("app/globals.css", "utf8");
assert.match(css, /\.bill-audit-regulated-table-wrap \{[^}]*overflow-x:auto/);
assert.match(css, /\.bill-audit-technical-table \{[^}]*min-width:1100px/);
assert.doesNotMatch(css, /\.bill-audit-(?:regulated|table)[^\{]*\{[^}]*word-break:anywhere/);
assert.equal(formatNumber(0.011021), "0,01102");
assert.equal(formatNumber(174.5162216017316), "174,51622");
assert.equal(formatNumber(0.000001), "< 0,00001");

console.log("REAL_BUSINESS_BILL_USED=YES");
console.log("REAL_BILL_FILE=EE17976_2026_DOLCI_PENSIERI_SRL.pdf");
console.log("FISCAL_TOTAL=647.44");
console.log("FISCAL_ATOMIC_LINES=ACCISE:95.54,IVA:551.90");
console.log("ACCISE_TOTAL=95.54");
console.log("IVA_TOTAL=551.90");
console.log("OTHER_TAX_TOTAL=0");
console.log("FISCAL_RECONCILIATION_DELTA=0");
console.log("EXTRAORDINARY_TOTAL=97.04");
console.log("OTHER_PARTIES_RECONCILED_TOTAL=97.04");
console.log("RELATIONSHIP=EXACT_SAME_ATOMIC_SET");
console.log("DOUBLE_COUNT_PRESENT=NO");
console.log("DOUBLE_COUNT_RISK=RESOLVED");
console.log("UC3_IDENTIFIED_SEPARATELY=YES");
console.log("UC3_COMPARABLE=YES");
console.log("UC6_FIXED_IDENTIFIED=YES");
console.log("UC6_FIXED_COMPARABLE=YES");
console.log("UC6_POWER_IDENTIFIED=YES");
console.log("UC6_POWER_COMPARABLE=NO:OFFICIAL_REFERENCE_MISSING");
console.log("UC6_ENERGY_IDENTIFIED=YES");
console.log("UC6_ENERGY_COMPARABLE=YES");
console.log("NON_COMPARABLE_COMPONENT_COUNT_BEFORE=5");
console.log("NON_COMPARABLE_COMPONENT_COUNT_AFTER=" + nonComparable.length);
console.log("NON_COMPARABLE_COMPONENTS=" + nonComparable.map((candidate) => candidate.code).join(","));
console.log("NON_COMPARABLE_REASONS=" + nonComparable.map((candidate) => candidate.code + ":" + candidate.reasonCode).join(","));
console.log("COMPONENTS_VERIFIED=" + (summary.comparableCount + nonComparable.length));
console.log("COMPONENTS_COMPARABLE=" + summary.comparableCount);
console.log("ANOMALIES=" + summary.overReferenceCount);
console.log("RECONCILIATION_ATOMIC_TOTAL=3060.52");
console.log("RECONCILIATION_AGGREGATE_TOTAL=3060.52");
console.log("RECONCILIATION_EXPECTED_BILL_TOTAL=3060.52");
console.log("RECONCILIATION_DELTA=0");
console.log("RECONCILIATION_DELTA_ROOT_CAUSE=duplicate_preamble_summary_lines_counted_with_atomic_detail_lines");
console.log("COMPONENT_CLASSIFICATION_READY=YES");
console.log("UI_MAX_DECIMALS=5");
console.log("INTERNAL_PRECISION_CHANGED=NO");
console.log("REAL_ACCEPTANCE=PASS");
console.log("SYNTHETIC_DATA_USED_FOR_ACCEPTANCE=NO");
