import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { auditElectricityBill, normalizeAppliedPun } from "../app/lib/foundation/bill-regulatory-audit.ts";
import { toPublicDocument, LocalBillRepository } from "../app/lib/foundation/real-bill.ts";
import { attachOfficialPun } from "../app/lib/market/pun-reference.ts";
import { LocalMarketArchiveRepository } from "../app/lib/market/repository.ts";

const ui = await readFile(new URL("../app/components/BillOperationalPanel.tsx", import.meta.url), "utf8");
const escape = (value) => value.replace(/[.*+?^()|[\]\\]/g, "\\$&");
const requiredLabels = [
  "FORNITURA", "CONSUMI", "OFFERTA ATTUALE", "COMPOSIZIONE COSTO", "VERIFICA BOLLETTA",
  "STATO ANALISI", "ANALISI PARZIALE", "ANOMALIE CONFERMATE", "COPERTURA FONTI UFFICIALI",
  "VERIFICABILITÀ DELLA BOLLETTA", "COMPONENTI REGOLATE ARERA", "DISPACCIAMENTO", "CAPACITY MARKET",
  "DETTAGLIO ANALISI", "PROVENIENZA DOCUMENTALE",
];
for (const label of requiredLabels) assert.match(ui, new RegExp(escape(label)));
for (const label of ["Domestico", "Residente", "Mercato libero", "Bassa tensione (BT)", "€/kWh", "F1", "F2", "F3", "Fonte: GME", "Fonte fiscale non ancora verificata", "Contratto necessario"]) assert.match(ui, new RegExp(escape(label)));
for (const code of ["NETWORK_FIXED", "METERING_FIXED", "NETWORK_POWER", "NETWORK_ENERGY", "TRANSMISSION_ENERGY", "ASOS", "ARIM", "UC3", "UC6", "DISPATCHING_TERNA_OPERATION", "DISPATCHING_ESSENTIAL_UNITS_REINTEGRATION", "CAPACITY_MARKET_OFF_PEAK"]) assert.match(ui, new RegExp(code));
assert.match(ui, /sourceCoverage\.ARERA_NETWORK/);
assert.match(ui, /sourceCoverage\.ARERA_SYSTEM_CHARGES/);
assert.match(ui, /sourceCoverage\.DISPATCHING/);
assert.match(ui, /sourceCoverage\.CAPACITY_MARKET/);
assert.match(ui, /sourceCoverage\.GME/);
assert.match(ui, /billAuditability\.ARERA_NETWORK/);
assert.match(ui, /billAuditability\.ARERA_SYSTEM_CHARGES/);
assert.doesNotMatch(ui, /CAPACITY_MARKET_PEAK/);
assert.doesNotMatch(ui, /Bolletta regolare/);
assert.doesNotMatch(ui, /Nessuna anomalia rilevata/);
assert.doesNotMatch(ui, /NON FATTURATA/);
assert.match(ui, /Nessuna anomalia confermata nelle componenti attualmente confrontabili/);
assert.match(ui, /<details className="bill-audit-collapsible bill-audit-wide"/);
assert.match(ui, /<summary>PROVENIENZA DOCUMENTALE<\/summary>/);
console.log("PROFILE_DOMESTIC_RESIDENT_VISIBLE=OK");
console.log("PROFILE_FREE_MARKET_VISIBLE=OK");
console.log("PROFILE_BT_VISIBLE=OK");
console.log("PUN_EUR_KWH_VISIBLE=OK");
console.log("GME_F1_F2_F3_EUR_KWH_VISIBLE=OK");
console.log("SOURCE_COVERAGE_NOT_CONFLATED_WITH_AUDITABILITY=OK");
console.log("NO_FAKE_CAPACITY_PEAK=OK");
console.log("ZERO_ANOMALIES_QUALIFIED_TEXT=OK");
console.log("NO_REGULAR_BILL_FALSE_CLAIM=OK");
console.log("TECHNICAL_DETAIL_COLLAPSIBLE=OK");
console.log("PROVENANCE_COLLAPSIBLE=OK");

const normalized = normalizeAppliedPun("0,196201", "EUR/KWH");
assert.equal(normalized.originalValue, 0.196201);
assert.equal(normalized.originalUnit, "EUR/KWH");
assert.equal(normalized.normalizedValue, 196.201);
assert.equal(normalized.normalizedUnit, "EUR/MWH");
assert.equal(normalized.status, "RESOLVED");
const unresolved = normalizeAppliedPun("0,196201", null);
assert.equal(unresolved.status, "UNRESOLVED");
assert.equal(unresolved.normalizedValue, null);
const unitAudit = auditElectricityBill({ billId: "ui", versionId: "v1", vector: "EE", customerType: "UNKNOWN", domesticResidenceStatus: "UNKNOWN", billingPeriod: { from: "2026-07-01", to: "2026-08-01" }, chargeLines: [] }, { appliedPunOriginalValue: 0.196201, appliedPunOriginalUnit: "EUR/KWH", officialGmeReferences: [{ month: "2026-07", value: 196.201, unit: "EUR/MWH", sourceReference: "GME", officialIdentifier: "GME" }] });
assert.equal(unitAudit.gme.appliedUnitStatus, "RESOLVED");
assert.equal(unitAudit.gme.delta, 0);
console.log("PUN_UNIT_NORMALIZATION=OK");
console.log("PUN_NO_COMPARISON_IF_UNIT_UNRESOLVED=OK");

const billId = "93d9b1f0-c748-4c66-ab32-b0673a96787e";
const repository = new LocalBillRepository();
const document = await repository.get("tenant_local-demo", billId);
assert.ok(document);
assert.equal(document.currentVersionId, document.versions.find((candidate) => candidate.versionNumber === 6)?.versionId);
const publicBill = await attachOfficialPun(toPublicDocument(document), new LocalMarketArchiveRepository());
const audit = publicBill.regulatoryAudit;
assert.ok(audit);
const matrix = audit.domesticResidentMatrix;
assert.ok(matrix);
assert.equal(audit.summary.overallStatus, "ANOMALIES_FOUND");
assert.equal(audit.summary.confirmedAnomalyCount, 1);
assert.equal(audit.summary.confirmedDifferenceCount, 2);
assert.equal(audit.summary.confirmedOverchargeCount, 1);
assert.equal(audit.summary.confirmedUnderchargeCount, 1);
assert.equal(audit.summary.confirmedOverchargeAmount, 0.05);
assert.equal(audit.summary.confirmedUnderchargeAmount, 0);
assert.equal(audit.summary.netConfirmedDifferenceAmount, 0.05);
assert.equal(audit.coverage.sourceCoverage.ARERA_NETWORK, "VERIFIED");
assert.equal(audit.coverage.sourceCoverage.ARERA_SYSTEM_CHARGES, "VERIFIED");
assert.equal(audit.coverage.sourceCoverage.DISPATCHING, "VERIFIED");
assert.equal(audit.coverage.sourceCoverage.CAPACITY_MARKET, "VERIFIED");
assert.equal(audit.coverage.sourceCoverage.GME, "VERIFIED");
assert.equal(audit.coverage.sourceCoverage.CONTRACT, "MISSING");
assert.equal(audit.coverage.sourceCoverage.TAX, "MISSING");
assert.equal(audit.coverage.billAuditability.ARERA_NETWORK, "DOCUMENT_DETAIL_REQUIRED");
assert.equal(audit.coverage.billAuditability.ARERA_SYSTEM_CHARGES, "PARTIAL");
assert.equal(audit.coverage.billAuditability.DISPATCHING, "CONTRACT_REQUIRED");
assert.equal(audit.coverage.billAuditability.CAPACITY_MARKET, "CONTRACT_REQUIRED");
assert.equal(audit.coverage.billAuditability.GME, "COMPLETE");
assert.equal(matrix.areraExpectedReferenceCount, 9);
assert.equal(matrix.areraAvailableReferenceCount, 9);
assert.equal(matrix.areraMissingReferenceCount, 0);
assert.equal(matrix.pun.appliedDisplayValue, 0.196201);
assert.deepEqual(matrix.pun.source.map((item) => [item.band, item.displayValue, item.displayUnit]), [["F1", 0.1542, "EUR/KWH"], ["F2", 0.16938, "EUR/KWH"], ["F3", 0.15226, "EUR/KWH"]]);
const arera = new Set(["NETWORK_FIXED", "METERING_FIXED", "NETWORK_POWER", "NETWORK_ENERGY", "TRANSMISSION_ENERGY", "ASOS", "ARIM", "UC3", "UC6"]);
assert.equal(matrix.components.filter((item) => arera.has(item.code)).length, 9);
const dispatching = matrix.components.filter((item) => ["DISPATCHING_TERNA_OPERATION", "DISPATCHING_ESSENTIAL_UNITS_REINTEGRATION"].includes(item.code));
assert.deepEqual(dispatching.map((item) => item.sourceValue?.sourceOriginalValue), [0.0652, 0.3041]);
const capacity = matrix.components.find((item) => item.code === "CAPACITY_MARKET_OFF_PEAK");
assert.ok(capacity);
assert.equal(capacity.sourceValue?.sourceOriginalValue, 3.197);
assert.equal(capacity.sourceValue?.sourceOriginalUnit, "EUR/MWH");
assert.equal(capacity.sourceValue?.effectiveFrom, "2026-07-01");
assert.equal(capacity.sourceValue?.effectiveTo, "2026-10-01");
const powerDifference = audit.regulatedPassThrough?.items.find((item) => item.code === "NETWORK_POWER");
assert.ok(powerDifference);
assert.equal(powerDifference.billAmount, 5.93);
assert.equal(powerDifference.estimatedAmountAtOfficialRate, 5.88);
assert.equal(powerDifference.amountDifference, 0.05);
assert.equal(powerDifference.unitRateDifferencePercent, 0.8504);
assert.equal(powerDifference.outcome, "SCOSTAMENTO");
const dispatchingDifference = audit.regulatedPassThrough?.items.find((item) => item.code === "DISPATCHING");
assert.equal(dispatchingDifference?.outcome, "SCOSTAMENTO");
assert.equal(dispatchingDifference?.status, "INFERIORE_AL_RIFERIMENTO");
assert.equal(dispatchingDifference?.comparisonResult, "CUSTOMER_UNDERCHARGE");
assert.equal(dispatchingDifference?.comparable, true);
assert.equal(dispatchingDifference?.authority, "ARERA");
assert.equal(dispatchingDifference?.officialIdentifier, "ARERA_DOMESTIC_FREE_2026");
assert.equal(dispatchingDifference?.normalizedOfficialRate, 0.038464);
assert.equal(dispatchingDifference?.unitRateDifference, -0.027963);
assert.equal(dispatchingDifference?.estimatedAmountAtOfficialRate, 15.27);
assert.equal(dispatchingDifference?.amountDifference, null);
const capacityDifference = audit.regulatedPassThrough?.items.find((item) => item.code === "CAPACITY_MARKET");
assert.equal(capacityDifference?.outcome, "COINCIDE");
assert.equal(capacityDifference?.comparable, true);
assert.equal(capacityDifference?.authority, "ARERA");
assert.equal(capacityDifference?.officialIdentifier, "219/2026/R/eel");
assert.equal(capacityDifference?.normalizedOfficialRate, 0.024466);
assert.equal(capacityDifference?.unitRateDifference, 0);
assert.equal(capacityDifference?.unitRateDifferencePercent, 0);
assert.equal(capacityDifference?.upstreamReferences[0]?.normalizedValue, 0.003197);
const asosDifference = audit.regulatedPassThrough?.items.find((item) => item.code === "ASOS");
assert.equal(asosDifference?.outcome, "COINCIDE");
assert.equal(asosDifference?.status, "CONFORME");
assert.equal(asosDifference?.comparable, true);
assert.equal(asosDifference?.billAmount, 12.51);
assert.equal(asosDifference?.estimatedAmountAtOfficialRate, 12.51);
const arimDifference = audit.regulatedPassThrough?.items.find((item) => item.code === "ARIM");
assert.equal(arimDifference?.outcome, "COINCIDE");
assert.equal(arimDifference?.status, "CONFORME");
assert.equal(arimDifference?.comparable, true);
assert.equal(arimDifference?.billAmount, 0.65);
assert.equal(capacityDifference?.amountDifference, null);
assert.match(ui, /Riconciliazione fattura/);
assert.match(ui, /Conformi/);
assert.match(ui, /Superiori al riferimento/);
assert.match(ui, /Inferiori al riferimento/);
assert.match(ui, /Maggior costo economico confermato/);
assert.match(ui, /SUPERIORE AL RIFERIMENTO/);
assert.match(ui, /Scostamento unitario/);
assert.match(ui, new RegExp("€/kW/mese"));
assert.match(ui, /Riferimento upstream TERNA/);
assert.match(ui, /Conforme al riferimento ARERA/);
assert.match(ui, /non utilizzato per il confronto customer-facing/);
assert.doesNotMatch(ui, /-0,06/);
assert.doesNotMatch(ui, /Illecito|IrregolaritÃ |Sovrafatturazione/);
console.log("ARERA_REFERENCE_DETAIL_VISIBLE=OK");
console.log("DISPATCHING_REFERENCE_DETAIL_VISIBLE=OK");
console.log("CAPACITY_OFF_PEAK_VISIBLE=OK");
console.log("PASS_THROUGH_DIFFERENCE_REPORTED=OK");
console.log("NETWORK_POWER_OVERCHARGE_VISIBLE=OK");
console.log("NETWORK_POWER_BILL_AMOUNT_5_93=OK");
console.log("NETWORK_POWER_EXPECTED_AMOUNT_5_88=OK");
console.log("NETWORK_POWER_DIFFERENCE_PLUS_0_05=OK");
console.log("NETWORK_POWER_PERCENT_PLUS_0_8504=OK");
console.log("NO_OLD_MINUS_0_06_VALUE=OK");
console.log("DISPATCHING_NO_FALSE_DIFFERENCE=OK");
console.log("CAPACITY_NO_FALSE_DIRECT_COMPARISON=OK");
console.log("UPSTREAM_TERNA_LABELLED_AS_UPSTREAM=OK");
console.log("CONFIRMED_OVERCHARGE_TOTAL_CORRECT=OK");
console.log("UNDERCHARGE_SEPARATE_FROM_OVERCHARGE=OK");
console.log("NO_LEGAL_FALSE_CLAIM=OK");
console.log("CONTRACT_REQUIRED_VISIBLE=OK");
console.log("TAX_NOT_VERIFIED_VISIBLE=OK");
console.log("ARERA_EXPECTED_9_AVAILABLE_9_MISSING_0=OK");
console.log("bill audit UI smoke: ok");
