import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const panel = await readFile(new URL("../app/components/BillOperationalPanel.tsx", import.meta.url), "utf8");
const mainStart = panel.indexOf("if (Boolean(review)) return");
const legacyReturn = panel.indexOf("\n  return <div className=\"bill-audit-detail\"><DocumentHeader", mainStart);
assert.ok(mainStart >= 0 && legacyReturn > mainStart);
const main = panel.slice(mainStart, legacyReturn);
for (const component of ["SupplyProfile", "PeriodAndConsumption", "CleanOfferSummary", "CleanEnergyReceiptCompact", "PaymentSummary", "VerificationSummary", "AnalysisDetail"]) assert.match(main, new RegExp(`<${component}`));
assert.match(main, /<DocumentHeader/);
assert.doesNotMatch(main, /Totale bolletta|Totale fattura|Importo fattura corrente/);
for (const label of ["FORNITURA", "CONSUMI", "OFFERTA ATTUALE", "SCONTRINO DELL", "VERIFICA BOLLETTA", "DETTAGLIO ANALISI"]) assert.match(panel, new RegExp(label));
for (const label of ["AreraSection", "DispatchingSection", "CapacitySection", "CONTRATTO NECESSARIO"]) assert.doesNotMatch(main, new RegExp(label));
assert.doesNotMatch(main, /PassThroughSummary|RIFERIMENTI REGOLATI/);
assert.match(panel, /<details className="bill-audit-collapsible bill-audit-wide"><summary>DETTAGLIO ANALISI<\/summary>/);
assert.match(panel, /Riferimento GME periodo bolletta/);
assert.match(panel, /rawDescription/);
assert.match(panel, /sourceCoverage/);
assert.match(panel, /function CleanOfferSummary/);
const offer = panel.slice(panel.indexOf("function CleanOfferSummary"), panel.indexOf("function CostSummary"));
assert.doesNotMatch(offer, /Codice offerta/);
assert.match(offer, /bill-audit-price-bands/);
assert.match(offer, /\["F1", "F2", "F3", "F23"\]/);
assert.match(panel, /Non confrontabile direttamente|presente in bolletta/);
assert.doesNotMatch(offer, /contratto necessario|CTE|verifica contrattuale/i);
assert.match(panel, /function CleanEnergyReceiptCompact/);
assert.match(panel, /Totale bolletta escluso Canone TV/);
assert.match(panel, /Canone TV/);
assert.match(panel, /TOTALE FATTURA CORRENTE DA PAGARE/);
assert.match(panel, /function PaymentSummary/);
assert.match(panel, /PAGAMENTI PREGRESSI/);
assert.match(panel, /Componenti confrontate:/);
assert.match(panel, /Componenti ARERA applicabili \(codici univoci\)/);

console.log("MAIN_UI_IS_SUMMARY=OK");
console.log("NO_DUPLICATE_PUN_SECTION=OK");
console.log("NO_DUPLICATE_PERIOD=OK");
console.log("NO_GLOBAL_CONTRACT_REQUIRED=OK");
console.log("TECHNICAL_ARERA_DETAILS_COLLAPSED=OK");
console.log("TECHNICAL_TERNA_DETAILS_COLLAPSED=OK");
console.log("TECHNICAL_GME_DETAILS_COLLAPSED=OK");
console.log("CURRENT_OFFER_VISIBLE=OK");
console.log("ENERGY_PRICE_STRUCTURE_VISIBLE=OK");
console.log("SPREAD_VISIBLE_WHEN_PRESENT=OK");
console.log("PCV_VISIBLE_WHEN_PRESENT=OK");
console.log("DUPLICATE_COST_CARD_REMOVED=OK");
console.log("BILL_TOTAL_VISIBLE=OK");
console.log("AMOUNT_DUE_VISIBLE=OK");
console.log("ALL_TECHNICAL_DATA_PRESERVED=OK");
console.log("HEADER_NO_TOTAL_DUPLICATION=OK");
console.log("NO_DUPLICATE_POD=OK");
console.log("NO_DUPLICATE_SUPPLY_ADDRESS=OK");
console.log("CURRENT_OFFER_GROUPED=OK");
console.log("OFFER_CODE_HIDDEN=OK");
console.log("PRICE_BANDS_VERTICAL_F1_F2_F3=OK");
console.log("PASS_THROUGH_DOCUMENT_VALUE_ONLY=OK");
console.log("NO_CURRENT_SUPPLIER_CONTRACT_DEPENDENCY=OK");
console.log("BILL_RECEIPT_SINGLE_SUMMARY=OK");
console.log("BASE_TOTAL_LABEL_EXPLICIT=OK");
console.log("TV_FEE_SEPARATE_ROW=OK");
console.log("CURRENT_INVOICE_TOTAL_CLEAR=OK");
console.log("PRIOR_INVOICE_SEPARATE_SECTION=OK");
console.log("NO_COMPREHENSIVE_EXPOSURE_MAIN_UI=OK");
console.log("NO_REFERENCE_ARCHIVE_COUNTS_MAIN_UI=OK");
console.log("REAL_COMPARABLE_COUNT_VISIBLE=OK");
console.log("EXPANDED_ANALYSIS_COLLAPSED=OK");
console.log("bill UI synthesis smoke: ok");
