import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { syntheticElectricityCte, syntheticGasCte } from "../app/lib/cte/synthetic-fixtures.ts";
import { createCteArchive, createCteCorrection, approveCteArchive, rejectCteArchive } from "../app/lib/cte/archive/service.ts";
import { LocalCteArchiveRepository } from "../app/lib/cte/archive/repository.ts";
import { validateElectricityCte } from "../app/lib/cte/validation.ts";
import { syntheticElectricityPun, syntheticGasPsv } from "../app/lib/energy/synthetic-fixtures.ts";
import { createMarketArchive, approveMarketArchive, queryApprovedHistoricalMarketData } from "../app/lib/market/service.ts";
import { LocalMarketArchiveRepository } from "../app/lib/market/repository.ts";

const root = await mkdtemp(path.join(tmpdir(), "cte-market-archive-"));
const eeRoot = path.join(root, "cte");
const marketRoot = path.join(root, "market");
const tenantA = "tenant_archive-a";
const tenantB = "tenant_archive-b";
const clone = (value) => structuredClone(value);
const draft = (value) => { const result = clone(value); result.tenantId = tenantA; result.approval = { status: "DRAFT", reason: "IMPORTED_FOR_REVIEW" }; return result; };
const fails = async (operation, code) => assert.rejects(operation, (error) => error?.code === code || error?.message === code);

try {
  const cte = new LocalCteArchiveRepository(eeRoot);
  const ee = await createCteArchive(cte, { tenantId: tenantA, contract: draft(syntheticElectricityCte), now: "2026-08-01T00:00:00.000Z" });
  assert.equal(ee.versions[0].status, "DRAFT");
  const approvedEe = await approveCteArchive(cte, tenantA, ee.archiveId, ee.currentWorkingVersionId, "reviewer-ee", "ee-decision", "2026-08-02T00:00:00.000Z");
  assert.equal(approvedEe.currentApprovedVersionId, approvedEe.currentWorkingVersionId);
  assert.equal(approvedEe.versions[0].status, "APPROVED");
  const historyBeforeCorrection = structuredClone(approvedEe.history);
  const correctedContract = clone(syntheticElectricityCte); correctedContract.tenantId = tenantA;
  correctedContract.pricing.spread.amount = 0.014;
  const corrected = await createCteCorrection(cte, { tenantId: tenantA, archiveId: ee.archiveId, expectedVersionId: approvedEe.currentWorkingVersionId, contract: correctedContract, reason: "supplier correction", now: "2026-08-03T00:00:00.000Z" });
  const correctedApproved = await approveCteArchive(cte, tenantA, corrected.archiveId, corrected.currentWorkingVersionId, "reviewer-ee", "ee-decision-2", "2026-08-04T00:00:00.000Z");
  assert.equal(correctedApproved.versions[0].status, "EXPIRED");
  assert.equal(correctedApproved.currentApprovedVersionId, correctedApproved.currentWorkingVersionId);
  assert.deepEqual(approvedEe.history, historyBeforeCorrection);
  assert.equal((await cte.get(tenantB, ee.archiveId)), null);
  assert.equal((await cte.list(tenantB)).length, 0);
  const tamperedCte = await cte.get(tenantA, ee.archiveId);
  tamperedCte.history[0].actor = "tampered";
  await fails(cte.save(tamperedCte), "ARCHIVE_HISTORY_IMMUTABLE");

  const gas = await createCteArchive(cte, { tenantId: tenantA, contract: draft(syntheticGasCte), now: "2026-08-01T00:00:00.000Z" });
  const approvedGas = await approveCteArchive(cte, tenantA, gas.archiveId, gas.currentWorkingVersionId, "reviewer-gas", "gas-decision", "2026-08-02T00:00:00.000Z");
  assert.equal(approvedGas.vector, "GAS");
  const gasCorrection = clone(syntheticGasCte); gasCorrection.tenantId = tenantA;
  gasCorrection.vector = "EE";
  await fails(createCteCorrection(cte, { tenantId: tenantA, archiveId: gas.archiveId, expectedVersionId: approvedGas.currentWorkingVersionId, contract: gasCorrection }), "VECTOR_MISMATCH");
  const incomplete = clone(syntheticElectricityCte); incomplete.tenantId = tenantA;
  delete incomplete.pricing.spread;
  incomplete.approval = { status: "DRAFT", reason: "incomplete" };
  assert.throws(() => validateElectricityCte(incomplete));
  const overlap = await createCteArchive(cte, { tenantId: tenantA, archiveId: "cte-ee-overlap", contract: draft(syntheticElectricityCte), now: "2026-08-05T00:00:00.000Z" });
  await fails(approveCteArchive(cte, tenantA, overlap.archiveId, overlap.currentWorkingVersionId, "reviewer", ""), "ACTOR_REQUIRED");
  await fails(approveCteArchive(cte, tenantA, overlap.archiveId, overlap.currentWorkingVersionId, "reviewer", "overlap-decision", "2026-08-06T00:00:00.000Z"), "CTE_APPROVED_VALIDITY_OVERLAP");
  const rejected = await rejectCteArchive(cte, tenantA, overlap.archiveId, overlap.currentWorkingVersionId, "reviewer", "source not confirmed", "2026-08-06T00:00:00.000Z");
  assert.equal(rejected.versions[0].status, "REJECTED");

  const market = new LocalMarketArchiveRepository(marketRoot);
  const punDraft = clone(syntheticElectricityPun); punDraft.tenantId = tenantA; punDraft.approval = { status: "DRAFT", reason: "import" };
  const pun = await createMarketArchive(market, { tenantId: tenantA, record: punDraft, now: "2026-08-01T00:00:00.000Z" });
  const punApproved = await approveMarketArchive(market, tenantA, pun.archiveId, "reviewer", "pun-decision", "2026-08-02T00:00:00.000Z");
  assert.equal(punApproved.status, "APPROVED");
  const punV2Record = clone(syntheticElectricityPun); punV2Record.tenantId = tenantA; punV2Record.recordId = "pun-ee-v2"; punV2Record.version = "2"; punV2Record.approval = { status: "DRAFT", reason: "correction" };
  const punV2 = await createMarketArchive(market, { tenantId: tenantA, record: punV2Record, now: "2026-08-03T00:00:00.000Z" });
  await approveMarketArchive(market, tenantA, punV2.archiveId, "reviewer", "pun-v2-decision", "2026-08-04T00:00:00.000Z");
  const psvDraft = clone(syntheticGasPsv); psvDraft.tenantId = tenantA; psvDraft.approval = { status: "DRAFT", reason: "import" };
  const psv = await createMarketArchive(market, { tenantId: tenantA, record: psvDraft, now: "2026-08-01T00:00:00.000Z" });
  await approveMarketArchive(market, tenantA, psv.archiveId, "reviewer", "psv-decision", "2026-08-02T00:00:00.000Z");
  const historicalPun = await queryApprovedHistoricalMarketData(market, tenantA, "2026-06-15", "EE");
  assert.equal(historicalPun.length, 1);
  assert.equal(historicalPun[0].archiveId, "pun-ee-v2");
  assert.equal((await queryApprovedHistoricalMarketData(market, tenantA, "2026-06-15", "GAS"))[0].index, "PSV");
  const duplicate = clone(syntheticElectricityPun); duplicate.tenantId = tenantA; duplicate.recordId = "pun-ee-duplicate"; duplicate.approval = { status: "DRAFT", reason: "duplicate" };
  const duplicateDraft = await createMarketArchive(market, { tenantId: tenantA, record: duplicate, now: "2026-08-03T00:00:00.000Z" });
  await fails(approveMarketArchive(market, tenantA, duplicateDraft.archiveId, "reviewer", "duplicate-decision", "2026-08-04T00:00:00.000Z"), "MARKET_APPROVED_DUPLICATE");
  const malformed = clone(syntheticGasPsv); malformed.tenantId = tenantA; malformed.f1 = { value: 1, currency: "EUR", unit: "EUR_PER_MWH" };
  await fails(createMarketArchive(market, { tenantId: tenantA, record: malformed }), "GAS_SCHEMA_MIXED");
  assert.equal((await market.list(tenantB)).length, 0);
  const tamperedMarket = await market.get(tenantA, pun.archiveId);
  tamperedMarket.record.source.name = "tampered";
  await fails(market.save(tamperedMarket), "ARCHIVE_VERSION_IMMUTABLE");
  await mkdir(path.join(eeRoot), { recursive: true });
  await writeFile(path.join(eeRoot, "metadata.json.stale.tmp"), "not-used", "utf8");
  assert.equal((await new LocalCteArchiveRepository(eeRoot).get(tenantA, ee.archiveId))?.archiveId, ee.archiveId);
  console.log("cte-market-archive smoke tests passed");
} finally {
  await rm(root, { recursive: true, force: true });
}
