import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import os from "node:os";
import { fetchAreraDomesticCdispdWorkbook, parseAreraDomesticCdispdXlsx, discoverAreraDomesticWorkbookUrl } from "../app/lib/foundation/arera-electricity-regulatory.ts";

const workbookName = (await readdir(os.tmpdir())).find((name) => /^Corrispettivi_libero_elettrico_domestico_20\d{2}\.xlsx$/i.test(name));
assert.ok(workbookName, "official workbook must be available in the system temp directory");
const workbookBytes = new Uint8Array(await readFile(`${os.tmpdir()}/${workbookName}`));
const stablePage = "https://www.arera.it/consumatori/valori-rete-oneri-domestici-ee";
const html = `<a href="https://www.arera.it/fileadmin/area_operatori/prezzi_e_tariffe/${workbookName}">file ufficiale</a>`;
const discovered = discoverAreraDomesticWorkbookUrl(html);
assert.match(discovered, /Corrispettivi_libero_elettrico_domestico_20\d{2}\.xlsx$/i);
const fetcher = async (url) => ({ status: 200, headers: { get(name) { return name.toLowerCase() === "content-type" && url.endsWith(".xlsx") ? "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" : "text/html"; } }, text: async () => html, arrayBuffer: async () => url.endsWith(".xlsx") ? workbookBytes.buffer.slice(workbookBytes.byteOffset, workbookBytes.byteOffset + workbookBytes.byteLength) : new TextEncoder().encode(html).buffer });
const workbook = await fetchAreraDomesticCdispdWorkbook(fetcher);
assert.equal(workbook.discoveryUrl, stablePage);
const imported = parseAreraDomesticCdispdXlsx({ body: workbook.bytes, sourceReference: workbook.url, retrievedAt: "2026-09-09T00:00:00.000Z", discoveryReference: workbook.discoveryUrl });
assert.deepEqual(imported.sheetNames, ["agosto 2026", "luglio 2026", "giugno 2026", "maggio 2026", "aprile 2026", "marzo 2026", "febbraio 2026", "gennaio 2026"]);
assert.equal(imported.records.length, 8);
assert.deepEqual(imported.records.sort((a, b) => a.effectiveFrom.localeCompare(b.effectiveFrom)).map((record) => record.normalizedValue), [0.025305, 0.023366, 0.016509, 0.015531, 0.015531, 0.019902, 0.038464, 0.018468]);
assert.equal(imported.records.every((record) => record.componentCode === "DISPATCHING_TOTAL"), true);
assert.equal(imported.records.every((record) => record.officialName === "CDISPD" && record.referenceDomain === "DISPATCHING" && record.contractPassThroughRequired === false && record.normalizedUnit === "EUR/KWH"), true);
assert.equal(imported.records.every((record) => record.effectiveTo !== null), true);
assert.equal(imported.records.find((record) => record.effectiveFrom === "2026-08-01")?.effectiveTo, "2026-09-01");
assert.equal(imported.records.every((record) => record.sourceSha256.length === 64 && record.confirmationSource === workbook.discoveryUrl), true);
assert.equal(imported.records.every((record) => record.applicationBasis.includes("dispacciamento + mercato della capacità")), true);
console.log("CDISPD_SOURCE_DISCOVERY_DYNAMIC=PASS");
console.log("CDISPD_MONTHLY_SHEETS=PASS");
console.log("CDISPD_JAN_AUG_EXPECTED_VALUES=PASS");
console.log("CDISPD_AGGREGATE_NO_DECOMPOSITION=PASS");
console.log("CDISPD_RESIDENCY_SOURCE_QA=PASS");
console.log("CDISPD_MONTHLY_INTERVALS=PASS");
console.log("CDISPD_LATEST_INTERVAL_BOUNDED=PASS");
console.log("CDISPD_PROVENANCE_CHECKSUM=PASS");
