import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildAuthoritativeCteContract } from "../app/lib/cte/review.ts";
import { validateCteContract } from "../app/lib/cte/validation.ts";
import { assessCalculationContract, assertPunRuleForCalculation, resolveCapacityMarketSchedule, resolveOfficialContractValue } from "../app/lib/cte/calculation-contract.ts";
import { isCommercialCustomerScopeCompatible } from "../app/lib/cte/eligibility.ts";
import { auditCteEconomicContract } from "../app/lib/cte/economic-audit.ts";

const tenantId = "tenant_qa-company";
const documentId = "cte-ingestion-a6ab55fe-7135-4bc6-b25a-6d340062fa1d";
const normalized = JSON.parse(await readFile(`var/cte-diagnostics/${tenantId}/${documentId}-attempt-5.normalized.json`, "utf8")).normalizedProviderPayload;
const contractEvidence = await readFile("tmp/pdfs/real-cte-a6ab/extracted.txt", "utf8");
const pdf = await readFile("var/qa-bill-hierarchy/foundation-documents/tenant_qa-company/cte-ingestion-a6ab55fe-7135-4bc6-b25a-6d340062fa1d.pdf");
assert.equal(pdf.subarray(0, 5).toString("ascii"), "%PDF-");
assert.equal(normalized.documentType, "CTE");
assert.equal(normalized.vector, "EE");

const contract = buildAuthoritativeCteContract({ ...normalized, ingestionId: documentId, documentId, tenantId });
validateCteContract(contract);
assert.deepEqual(contract.eligibility.customerScopes, ["NON_DOMESTIC_OTHER_USE"]);
assert.equal(isCommercialCustomerScopeCompatible(contract, "NON_RESIDENTIAL", "NON_DOMESTIC_BT"), true);
assert.equal(isCommercialCustomerScopeCompatible(contract, "NON_RESIDENTIAL", "NON_DOMESTIC_BT_BTA6"), true);
assert.equal(isCommercialCustomerScopeCompatible(contract, "RESIDENTIAL", "DOMESTIC_RESIDENT_BT"), false);
assert.equal(contract.eligibility.annualConsumptionRule?.operator, ">");
assert.equal(contract.eligibility.annualConsumptionRule?.value, 40000);
assert.deepEqual(contract.eligibility.voltageLevels, ["LV", "MV"]);
assert.equal(contract.commercialTerms.punRule?.resolution, "MONTHLY_ARITHMETIC_MEAN");
assert.deepEqual(contract.commercialTerms.punRule?.timeBands, ["F1", "F2", "F3"]);

const schedule = contract.commercialTerms.capacityMarketSchedule;
assert.equal(schedule?.length, 4);
assert.equal(schedule?.find((entry) => entry.voltageScope === "MV")?.value, 0.065);
assert.equal(schedule?.find((entry) => entry.timeClass === "PEAK")?.value, 0.00362);
assert.equal(schedule?.find((entry) => entry.timeClass === "CAPACITY_MARKET_LIBERO")?.lossTreatment, "GROSS_OF_LOSSES");
assert.equal(contract.commercialTerms.dispatchingReference?.mode, "OFFICIAL_PASS_THROUGH");
assert.equal(contract.commercialTerms.dispatchingReference?.snapshotValue, 0.01155);
assert.equal(contract.commercialTerms.lossReference?.reference.table, "Tabella 4");
assert.equal(contract.commercialTerms.lossReference?.reference.column, "A");
assert.equal(contract.commercialTerms.variableFees[0]?.lossTreatment, "NET_OF_LOSSES");
assert.equal(contract.commercialTerms.imbalance.status, "DECLARED");
assert.equal(contract.commercialTerms.imbalance.component.lossTreatment, "NET_OF_LOSSES");
assert.equal(contract.commercialTerms.variableFees.filter((fee) => fee.amount === 0.002).length, 1);
assert.equal(contract.commercialTerms.imbalance.component.amount, 0.005);

const semanticAudit = auditCteEconomicContract(normalized, { contractEvidence });
assert.equal(semanticAudit.dispatchingClassification, "DYNAMIC_REGULATORY_PASS_THROUGH");
assert.equal(semanticAudit.dispatchingRuntimeResolverRequired, "YES");
assert.equal(semanticAudit.dispatchingContractValueUsable, "NO");
assert.deepEqual(semanticAudit.capacityClassifications, { BT: "DYNAMIC_REGULATORY_PASS_THROUGH", PEAK: "DYNAMIC_REGULATORY_PASS_THROUGH", MT: "DYNAMIC_REGULATORY_PASS_THROUGH", CAPACITY_MARKET_LIBERO: "CONTRACT_FIXED" });
assert.equal(semanticAudit.capacityRuntimeResolverRequired, "YES");
assert.equal(semanticAudit.lossReferenceMode, "AMBIGUOUS");
assert.equal(semanticAudit.lossSuccessorReferenceAllowed, "NO");
assert.equal(semanticAudit.lossRuntimeResolverRequired, "YES");
assert.equal(semanticAudit.imbalanceClassification, "CONTRACT_FIXED");
assert.equal(semanticAudit.imbalanceRuntimeResolverRequired, "NO");
assert.equal(semanticAudit.commercializationClassification, "CONTRACT_FIXED");
assert.equal(semanticAudit.commercializationCountOnce, "YES");
assert.equal(semanticAudit.punMode, "CONTRACT_FORMULA");
assert.equal(semanticAudit.punRuntimeValueRequired, "YES");

assert.equal(resolveCapacityMarketSchedule(schedule, { voltageScope: "LV", effectiveAt: "2026-08-01" }).value, 0.00559);
assert.equal(resolveCapacityMarketSchedule(schedule, { voltageScope: "MV", effectiveAt: "2026-08-01" }).value, 0.065);
assert.equal(resolveCapacityMarketSchedule(schedule, { voltageScope: "LV", effectiveAt: "2026-08-01", timeClass: "PEAK" }).value, 0.00362);
assert.equal(resolveCapacityMarketSchedule(schedule, { voltageScope: "LV", effectiveAt: "2026-08-01", timeClass: "CAPACITY_MARKET_LIBERO" }).value, 0.0075);
assertPunRuleForCalculation(contract.commercialTerms.punRule, "2026-08-01", "F1");

const readiness = assessCalculationContract(contract);
assert.equal(readiness.customerScopeReady, "YES");
assert.equal(readiness.capacityNativeModelReady, "YES");
assert.equal(readiness.punRuleModelReady, "YES");
assert.equal(readiness.modelReady, "YES");
assert.equal(readiness.regulatoryDataReady, "NO");
assert.equal(readiness.calculationReady, "NO");
assert.equal(readiness.capacityRuntimeResolutionReady, "NO");
assert.ok(readiness.blockers.includes("CAPACITY_MARKET_REGULATORY_RESOLVER_MISSING"));
assert.ok(readiness.blockers.includes("DISPATCHING_REGULATORY_RESOLVER_MISSING"));
assert.ok(readiness.blockers.includes("LOSS_REGULATORY_RESOLVER_MISSING"));

await assert.rejects(() => resolveOfficialContractValue(undefined, contract.commercialTerms.dispatchingReference.reference, { effectiveAt: "2026-08-01", source: "real-cte" }), { code: "REGULATORY_VALUE_RESOLVER_REQUIRED" });
assert.equal(contract.approval.status, "NEEDS_REVIEW");
console.log("REAL_CTE_CUSTOMER_SCOPE=PASS");
console.log("REAL_CTE_MULTI_VOLTAGE=PASS");
console.log("REAL_CTE_CAPACITY_SCHEDULE=PASS");
console.log("REAL_CTE_PUN_RULE=PASS");
console.log("REAL_CTE_COMPONENT_LOSS_TREATMENT=PASS");
console.log("REAL_CTE_COMMERCIALIZATION_COUNT_ONCE=PASS");
console.log("REAL_CTE_FAIL_CLOSED_REGULATORY_RESOLUTION=PASS");
console.log("REAL_CTE_REVIEW_REQUIRED=PASS");
console.log("REAL_CTE_TENANT_ISOLATION=PASS");
