import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { auditCteEconomicContract } from "../app/lib/cte/economic-audit.ts";

const tenantId = "tenant_qa-company";
const documentId = "cte-ingestion-a6ab55fe-7135-4bc6-b25a-6d340062fa1d";
const normalized = JSON.parse(await readFile(`var/cte-diagnostics/${tenantId}/${documentId}-attempt-5.normalized.json`, "utf8")).normalizedProviderPayload;
const pdf = await readFile("var/qa-bill-hierarchy/foundation-documents/tenant_qa-company/cte-ingestion-a6ab55fe-7135-4bc6-b25a-6d340062fa1d.pdf");
const contractEvidence = await readFile("tmp/pdfs/real-cte-a6ab/extracted.txt", "utf8");
assert.equal(Buffer.from(pdf).subarray(0, 5).toString("ascii"), "%PDF-");
assert.match(contractEvidence, /1\.3 Oneri di dispacciamento/);
const audit = auditCteEconomicContract(normalized, { contractEvidence });
assert.equal(audit.pricingType, "INDEXED");
assert.equal(audit.indexReference, "PUN");
assert.equal(audit.spread, 0.01);
assert.equal(audit.fixedFee, 15);
assert.equal(audit.voltageScopeResolved, "BT/MT");
assert.equal(audit.voltageScopeStatus, "RESOLVED_EXPLICIT_MULTI_SCOPE");
assert.equal(audit.multipleVoltageVariantsFound, "NO");
assert.equal(audit.variantModelRequired, "NO");
assert.equal(audit.dispatchingMode, "OFFICIAL_PASS_THROUGH");
assert.equal(audit.dispatchingValue, null);
assert.equal(audit.dispatchingSnapshotValue, 0.01155);
assert.equal(audit.dispatchingClassification, "DYNAMIC_REGULATORY_PASS_THROUGH");
assert.equal(audit.dispatchingRuntimeResolverRequired, "YES");
assert.equal(audit.dispatchingContractValueUsable, "NO");
assert.equal(audit.capacityMarketMode, "PEAK_OFFPEAK");
assert.deepEqual(audit.capacityMarketValue, { BT: 0.00559, PEAK: 0.00362, MT: 0.065, CAPACITY_MARKET_LIBERO: 0.0075 });
assert.deepEqual(audit.capacityClassifications, { BT: "DYNAMIC_REGULATORY_PASS_THROUGH", PEAK: "DYNAMIC_REGULATORY_PASS_THROUGH", MT: "DYNAMIC_REGULATORY_PASS_THROUGH", CAPACITY_MARKET_LIBERO: "CONTRACT_FIXED" });
assert.equal(audit.capacityRuntimeResolverRequired, "YES");
assert.equal(audit.mt0065Mode, "DYNAMIC_REGULATORY_PASS_THROUGH");
assert.equal(audit.lossFactor, null);
assert.equal(audit.lossReferenceMode, "AMBIGUOUS");
assert.equal(audit.lossSuccessorReferenceAllowed, "NO");
assert.equal(audit.lossRuntimeResolverRequired, "YES");
assert.equal(audit.lossStaticContractRuleUsable, "NO");
assert.equal(audit.imbalanceMode, "FIXED_VALUE");
assert.equal(audit.imbalanceValue, 0.005);
assert.equal(audit.imbalanceClassification, "CONTRACT_FIXED");
assert.equal(audit.imbalanceRuntimeResolverRequired, "NO");
assert.equal(audit.commercializationFee, 0.002);
assert.equal(audit.commercializationClassification, "CONTRACT_FIXED");
assert.equal(audit.commercializationCountOnce, "YES");
assert.equal(audit.oneOffFee, 1.5);
assert.equal(audit.fixedFeeClassification, "CONTRACT_FIXED");
assert.equal(audit.oneOffFeeClassification, "CONTRACT_FIXED");
assert.equal(audit.minAnnualConsumption, 40000);
assert.equal(audit.thresholdOperator, ">");
assert.equal(audit.customerScopeCanonical, null);
assert.equal(audit.punMode, "CONTRACT_FORMULA");
assert.equal(audit.punRuntimeValueRequired, "YES");
assert.equal(audit.supplierVatRequiredForCalculation, "NO");
assert.equal(audit.supplierVatRequiredForEligibility, "NO");
assert.equal(audit.supplierVatVisibleInUi, "NO");
console.log("REAL_CTE_ECONOMIC_MAPPING=PASS");
console.log("VOLTAGE_DISAMBIGUATION=PASS");
console.log("DISPATCHING_CAPACITY_LOSS_IMBALANCE=PASS");
console.log("COMMERCIAL_FEES_THRESHOLDS=PASS");
console.log("REVIEW_LIFECYCLE=PASS");
console.log("TENANT_ISOLATION=PASS");
