import { createHash } from "node:crypto";

export type VersionLifecycle = "IMPORTED" | "VALIDATED" | "APPROVED" | "REJECTED";
const allowedTransitions: Readonly<Record<VersionLifecycle, readonly VersionLifecycle[]>> = { IMPORTED: ["VALIDATED", "APPROVED", "REJECTED"], VALIDATED: ["APPROVED", "REJECTED"], APPROVED: [], REJECTED: [] };
export function assertLifecycleTransition(from: VersionLifecycle, to: VersionLifecycle): void { if (!allowedTransitions[from].includes(to)) throw new Error("INVALID_LIFECYCLE_TRANSITION"); }
export interface ImmutableVersion<TPayload> { readonly entityId: string; readonly version: number; readonly parentVersionId: string | null; readonly supersedesVersionId: string | null; readonly reviewDecisionId: string | null; readonly createdAt: string; readonly lifecycle: VersionLifecycle; readonly payload: Readonly<TPayload>; }

function canonical(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; return `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`; }
function digest(value: unknown): string { return createHash("sha256").update(canonical(value)).digest("hex"); }

export class AppendOnlyVersionStore<TPayload extends object> {
  private readonly history = new Map<string, ImmutableVersion<TPayload>[]>();
  put(entityId: string, payload: TPayload, lifecycle: VersionLifecycle, reviewDecisionId: string | null = null, now = new Date().toISOString()): ImmutableVersion<TPayload> { const versions = this.history.get(entityId) ?? []; const last = versions[versions.length - 1]; if (!last && lifecycle !== "IMPORTED") throw new Error("INVALID_LIFECYCLE_TRANSITION"); if (last && digest(last.payload) !== digest(payload)) throw new Error("VERSION_CONFLICT"); if (last && last.lifecycle === lifecycle && last.reviewDecisionId === reviewDecisionId) return last; if (last) return this.transition(entityId, lifecycle, reviewDecisionId, now); return this.create(entityId, payload, lifecycle, reviewDecisionId, now, []); }
  transitionWithPayload(entityId: string, payload: TPayload, lifecycle: VersionLifecycle, reviewDecisionId: string | null = null, now = new Date().toISOString()): ImmutableVersion<TPayload> { const versions = this.history.get(entityId); if (!versions?.length) throw new Error("VERSION_SUBJECT_NOT_FOUND"); const last = versions[versions.length - 1]; if (digest(last.payload) === digest(payload) && last.lifecycle === lifecycle && last.reviewDecisionId === reviewDecisionId) return last; this.assertTransition(last.lifecycle, lifecycle); return this.create(entityId, payload, lifecycle, reviewDecisionId, now, versions); }
  transition(entityId: string, lifecycle: VersionLifecycle, reviewDecisionId: string | null, now = new Date().toISOString()): ImmutableVersion<TPayload> { const versions = this.history.get(entityId); if (!versions?.length) throw new Error("VERSION_SUBJECT_NOT_FOUND"); const last = versions[versions.length - 1]; this.assertTransition(last.lifecycle, lifecycle); return this.create(entityId, last.payload as TPayload, lifecycle, reviewDecisionId, now, versions); }
  private assertTransition(from: VersionLifecycle, to: VersionLifecycle): void { assertLifecycleTransition(from, to); }
  private create(entityId: string, payload: TPayload, lifecycle: VersionLifecycle, reviewDecisionId: string | null, now: string, versions: readonly ImmutableVersion<TPayload>[]): ImmutableVersion<TPayload> { const last = versions[versions.length - 1]; const version = (last?.version ?? 0) + 1; const record: ImmutableVersion<TPayload> = Object.freeze({ entityId, version, parentVersionId: last ? `${entityId}@${last.version}` : null, supersedesVersionId: last ? `${entityId}@${last.version}` : null, reviewDecisionId, createdAt: now, lifecycle, payload: Object.freeze({ ...payload }) }); this.history.set(entityId, [...versions, record]); return record; }
  historyFor(entityId: string): readonly ImmutableVersion<TPayload>[] { return [...(this.history.get(entityId) ?? [])]; }
  current(entityId: string): ImmutableVersion<TPayload> | null { const versions = this.history.get(entityId); return versions?.[versions.length - 1] ?? null; }
}
