import type { RegulatoryValueRecord } from "./regulatory-types.ts";

export type ReferenceDomain = "NETWORK" | "SYSTEM_CHARGES" | "DISPATCHING" | "CAPACITY_MARKET" | "MARKET_INDEX" | "TAX" | "CONTRACT";

const domains: Readonly<Record<string, ReferenceDomain>> = {
  S1_TOTAL: "NETWORK", S1_MEASURE: "NETWORK", S2_POWER: "NETWORK", S3_ENERGY_TRANSMISSION: "NETWORK",
  NETWORK_FIXED: "NETWORK", METERING_FIXED: "NETWORK", NETWORK_POWER: "NETWORK", NETWORK_ENERGY: "NETWORK", TRANSMISSION_ENERGY: "NETWORK",
  ASOS: "SYSTEM_CHARGES", ARIM: "SYSTEM_CHARGES", UC3: "SYSTEM_CHARGES", UC6: "SYSTEM_CHARGES",
  DISPATCHING: "DISPATCHING", DISPATCHING_TOTAL: "DISPATCHING", DISPATCHING_UPLIFT: "DISPATCHING",
  DISPATCHING_UPLIFT_ATT_MSDMB: "DISPATCHING", DISPATCHING_UPLIFT_ATT_DED: "DISPATCHING", DISPATCHING_UPLIFT_RUPL: "DISPATCHING",
  DISPATCHING_ESSENTIAL_UNITS: "DISPATCHING", DISPATCHING_ESSENTIAL_UNITS_ORDINARY: "DISPATCHING", DISPATCHING_ESSENTIAL_UNITS_REINTEGRATION: "DISPATCHING",
  DISPATCHING_TERNA_OPERATION: "DISPATCHING", DISPATCHING_EXTRAORDINARY_MODULATION: "DISPATCHING", DISPATCHING_WIND_COMPENSATION: "DISPATCHING", DISPATCHING_OTHER_ITEMS: "DISPATCHING",
  CAPACITY_MARKET: "CAPACITY_MARKET", CAPACITY_MARKET_PEAK: "CAPACITY_MARKET", CAPACITY_MARKET_OFF_PEAK: "CAPACITY_MARKET",
};

export function referenceDomainForComponent(componentCode: string): ReferenceDomain | null {
  return domains[componentCode] ?? null;
}

export function referenceDomainOf(record: Pick<RegulatoryValueRecord, "componentCode" | "referenceDomain">): ReferenceDomain | null {
  return record.referenceDomain ?? referenceDomainForComponent(record.componentCode);
}
