/** Server-side analyst catalog. These values are deliberately not emitted as wire-schema enums. */
export const BILL_ANALYST_ITEM_CODES = [
  "INVOICE_NUMBER", "CUSTOMER_COMPANY_NAME", "CUSTOMER_VAT_NUMBER", "BILLING_ADDRESS", "COMPREHENSIVE_AMOUNT",
  "SUPPLY_ADDRESS", "SUPPLY_CITY", "SUPPLY_POSTAL_CODE", "SUPPLY_PROVINCE",
  "SUPPLY_USE_CATEGORY_RAW", "DOMESTIC_RESIDENCE_STATUS_RAW", "CONTRACTUAL_TARIFF_CATEGORY_RAW", "MARKET_REGIME_RAW", "VOLTAGE_CLASS_RAW",
  "SUPPLY_USE_CATEGORY", "DOMESTIC_RESIDENCE_STATUS", "CONTRACTUAL_TARIFF_CATEGORY", "MARKET_REGIME", "VOLTAGE_CLASS",
  "NOMINAL_VOLTAGE", "POWER_COMMITTED", "POWER_AVAILABLE",
  "BILLING_PERIOD_RAW", "BILL_ISSUE_DATE", "BILL_DUE_DATE", "CONTRACT_START_DATE", "ECONOMIC_CONDITIONS_START_DATE", "ECONOMIC_EXPIRY", "CONTRACT_EXPIRY", "CONTRACT_INDEFINITE", "EARLY_TERMINATION_FEE_PRESENT", "EARLY_TERMINATION_FEE_VALUE",
  "PAYMENT_METHOD", "PAYMENT_REGULARITY", "OUTSTANDING_AMOUNT", "PREVIOUS_UNPAID_EVIDENCE",
  "PUN_SINGLE", "PUN_F1", "PUN_F2", "PUN_F3", "SPREAD", "INDEX_NAME", "PRICE_MECHANISM_RAW", "PRICE_TIME_STRUCTURE_RAW", "PRICE_FORMULA_RAW", "PRICE_F1", "PRICE_F2", "PRICE_F3", "PRICE_F23", "MONORARIO_PRICE", "FIXED_PRICE", "LOSS_FACTOR", "ENERGY_INDEX", "ENERGY_SPREAD", "ENERGY_FIXED_PRICE",
  "PCV", "COMMERCIALIZATION_FIXED_FEE", "COMMERCIALIZATION_VARIABLE_FEE", "SELLER_FIXED_FEE", "SELLER_ENERGY_FEE",
  "NETWORK_LOSS_CHARGE", "DISPATCHING_SELLER_CHARGE", "CAPACITY_MARKET_SELLER_CHARGE", "BALANCING_CHARGE",
  "OTHER_SELLER_ENERGY_CHARGE", "OTHER_SELLER_FIXED_CHARGE",
  "DISPATCHING", "IMBALANCE", "CAPACITY_MARKET", "SELLER_FIXED", "COMMERCIALIZATION",
  "NETWORK_SYSTEM", "NETWORK_FIXED", "POWER_CHARGE", "ASOS", "ARIM", "EXCISE", "VAT",
  "DISPATCHING_TERNA_OPERATION", "DISPATCHING_ESSENTIAL_UNITS_REINTEGRATION", "GME_MARKET_REFERENCE",
  "CANONE_RAI", "TV_FEE", "INTERESSI_MORA", "LATE_PAYMENT", "CMOR", "ADMINISTRATIVE_FEES", "DELIVERY_DISCOUNT", "SERVIZI_AGGIUNTIVI", "RICALCOLI", "RESTITUZIONI", "ADDEBITI", "ACCREDITI", "ALTRE_PARTITE",
  "DISCOUNT", "BONUS", "RECALCULATION", "OTHER_CHARGE", "UNCLASSIFIED_BILL_CHARGE", "UNKNOWN",
] as const;

export type BillAnalystItemCode = typeof BILL_ANALYST_ITEM_CODES[number];

// Domain compatibility aliases remain server-side only and are normalized before persistence.
const BILL_ANALYST_CODE_ALIASES: Readonly<Record<string, BillAnalystItemCode>> = {
  SUPPLY_USE_CATEGORY: "SUPPLY_USE_CATEGORY_RAW",
  DOMESTIC_RESIDENCE_STATUS: "DOMESTIC_RESIDENCE_STATUS_RAW",
  CONTRACTUAL_TARIFF_CATEGORY: "CONTRACTUAL_TARIFF_CATEGORY_RAW",
  MARKET_REGIME: "MARKET_REGIME_RAW",
  VOLTAGE_CLASS: "VOLTAGE_CLASS_RAW",
  SUPPLY_CAP: "SUPPLY_POSTAL_CODE",
  NOMINAL_SUPPLY_VOLTAGE: "NOMINAL_VOLTAGE",
  ECONOMIC_CONDITIONS_EXPIRY_DATE: "ECONOMIC_EXPIRY",
  CONTRACT_EXPIRY_DATE: "CONTRACT_EXPIRY",
  CONTRACT_EXPIRY_STATUS: "CONTRACT_INDEFINITE",
  PUN_APPLIED_MONTHLY: "PUN_SINGLE",
  PUN_APPLIED_F1: "PUN_F1",
  PUN_APPLIED_F2: "PUN_F2",
  PUN_APPLIED_F3: "PUN_F3",
  PUN: "PUN_SINGLE",
  SELLER_SPREAD: "SPREAD",
  DISPACCIAMENTO: "DISPATCHING",
  POWER: "POWER_CHARGE",
  OTHER: "OTHER_CHARGE",
  ENERGY_PRICE: "ENERGY_INDEX",
  FIXED_PRICE: "ENERGY_FIXED_PRICE",
  COMMERCIALIZATION_FEE: "COMMERCIALIZATION_FIXED_FEE",
  COMMERCIALIZATION_FIXED: "COMMERCIALIZATION_FIXED_FEE",
  COMMERCIALIZATION_VARIABLE: "COMMERCIALIZATION_VARIABLE_FEE",
  PCV_QUOTA: "PCV",
  TV: "CANONE_RAI",
  LATE_PAYMENT_CHARGE: "INTERESSI_MORA",
  BALANCING: "BALANCING_CHARGE",
  RAI: "CANONE_RAI",
  INTEREST_ON_ARREARS: "INTERESSI_MORA",
  ADDITIONAL_SERVICES: "SERVIZI_AGGIUNTIVI",
  REFUNDS: "RESTITUZIONI",
  DEBITS: "ADDEBITI",
  CREDITS: "ACCREDITI",
  OTHER_ITEMS: "ALTRE_PARTITE",
};

export function normalizeAnalystItemCode(value: string): BillAnalystItemCode {
  const key = value.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  if (BILL_ANALYST_ITEM_CODES.includes(key as BillAnalystItemCode)) return key as BillAnalystItemCode;
  return BILL_ANALYST_CODE_ALIASES[key] ?? "UNKNOWN";
}

// Structured extraction uses the same server catalog; no catalog is copied into Anthropic JSON Schema.
export const BILL_EXTENDED_FACT_CODES = BILL_ANALYST_ITEM_CODES;
export type BillExtendedFactCode = typeof BILL_EXTENDED_FACT_CODES[number];

export const BILL_ECONOMIC_CHARGE_CODES = [
  "PUN_SINGLE", "PUN_F1", "PUN_F2", "PUN_F3", "SPREAD", "DISPATCHING", "IMBALANCE", "CAPACITY_MARKET",
  "SELLER_FIXED", "COMMERCIALIZATION", "NETWORK_SYSTEM", "NETWORK_FIXED", "NETWORK_ENERGY", "NETWORK_POWER", "METERING_FIXED", "TRANSMISSION_ENERGY", "POWER_CHARGE", "ASOS", "ARIM", "UC3", "UC6", "ARERA_NETWORK", "ARERA_SYSTEM_CHARGES",
  "ENERGY_INDEX", "ENERGY_SPREAD", "ENERGY_FIXED_PRICE", "PCV", "COMMERCIALIZATION_FIXED_FEE", "COMMERCIALIZATION_VARIABLE_FEE", "SELLER_FIXED_FEE", "SELLER_ENERGY_FEE",
  "NETWORK_LOSS_CHARGE", "DISPATCHING_SELLER_CHARGE", "CAPACITY_MARKET_SELLER_CHARGE", "BALANCING_CHARGE", "OTHER_SELLER_ENERGY_CHARGE", "OTHER_SELLER_FIXED_CHARGE",
  "DISPATCHING_TERNA_OPERATION", "DISPATCHING_ESSENTIAL_UNITS_REINTEGRATION", "GME_MARKET_REFERENCE", "EXCISE", "VAT", "TAX_SUBTOTAL", "BILL_TOTAL", "AMOUNT_DUE", "PRIOR_BALANCE", "COMPREHENSIVE_AMOUNT", "CANONE_RAI", "TV_FEE", "INTERESSI_MORA", "LATE_PAYMENT", "CMOR", "ADMINISTRATIVE_FEES", "DELIVERY_DISCOUNT", "SERVIZI_AGGIUNTIVI", "RICALCOLI", "RESTITUZIONI", "ADDEBITI", "ACCREDITI", "ALTRE_PARTITE", "DISCOUNT", "BONUS", "RECALCULATION", "OTHER_CHARGE", "UNCLASSIFIED_BILL_CHARGE", "UNKNOWN",
] as const;
export type BillEconomicChargeLineCode = typeof BILL_ECONOMIC_CHARGE_CODES[number];
